### YamlMime:YamlDocument
documentType: LandingData
title: Ansible v dokumentaci k Azure
metadata:
  title: "Ansible v dokumentaci k Azure – kurzy, ukázky, odkazy a prostředky"
  meta.description: Learn how to use Ansible to automate cloud provisioning, configuration management, and application deployments.
  services: terraform
  author: tomarcher
  manager: routlaw
  ms.service: ansible
  ms.tgt_pltfrm: na
  ms.devlang: devops
  ms.topic: landing-page
  ms.date: 01/18/2018
  ms.author: tarcher
  ms.openlocfilehash: b3e9ae46eaef25af6d290231a48850cd1ef43153
  ms.sourcegitcommit: ded74961ef7d1df2ef8ffbcd13eeea0f4aaa3219
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 01/29/2018
abstract:
  description: "Použití <a href=\"http://www.ansible.com\">Ansible</a> k automatizaci zřizování cloudu, správě konfigurací a nasazení aplikací."
sections:
- title: "Zprovoznění během 5 minut"
  items:
  - type: paragraph
    text: "Nakonfigurujte Ansible a použijte ho k vytvoření virtuálního počítače s Linuxem v Azure."
  - type: list
    style: icon48
    items:
    - image:
        src: /azure/media/index/azure_dev-9.svg
      text: Konfigurace Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: "Vytvoření virtuálního počítače s Linuxem"
      href: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: "Podrobné kurzy"
  items:
  - type: paragraph
    text: "Zjistěte, jak použít Ansible k vytvoření a správě výpočetní a síťové infrastruktury Azure."
  - type: list
    style: unordered
    items:
    - html: "<a href=\"/azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json\">Vytvořte virtuální počítač s Linuxem, včetně virtuální sítě, veřejné IP adresy a virtuální síťové karty.</a>"
    - html: "<a href=\"./ansible-run-playbook-in-cloudshell\">Připojte se k virtuálnímu počítači Azure a spusťte playbook Ansible v Cloud Shellu.</a>"
    - html: "<a href=\"./ansible-manage-azure-dynamic-inventories\">Vytvořte a spravujte dynamický inventář vašich prostředků Azure.</a>"
- title: "Referenční informace"
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: Role playbooku
      html: <p><a href="https://galaxy.ansible.com/Azure/azure_modules/">azure_module</a></p><p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>
    - title: Verze a funkce
      html: "<p><a href=\"./ansible-matrix.md\">Matice funkcí pro moduly a role</a></p>"
