- name: Ansible v Azure
  href: ./index.yml
- name: Přehled
  items:
    - name: O Ansible v Azure
      href: ./ansible-overview.md
- name: Šablony Rychlý start
  expanded: true
  items:
    - name: Instalace a konfigurace Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure
      maintainContext: true
    - name: Vytvoření virtuálního počítače s Linuxem
      href: /azure/virtual-machines/linux/ansible-create-vm
      maintainContext: true
- name: Kurzy
  items:
    - name: Vytvoření kompletního virtuálního počítače s Linuxem
      href: /azure/virtual-machines/linux/ansible-create-complete-vm
      maintainContext: true
    - name: Spuštění playbooku v Cloud Shellu
      href: ./ansible-run-playbook-in-cloudshell.md
      maintainContext: true
    - name: Správa dynamického inventáře
      href: ./ansible-manage-azure-dynamic-inventories.md
      maintainContext: true
- name: Referenční informace
  items:
    - name: Role playbooku
      items:
        - name: azure_module
          href: 'https://galaxy.ansible.com/Azure/azure_modules/'
        - name: azure_preview_module
          href: 'https://galaxy.ansible.com/Azure/azure_preview_modules'
    - name: Verze a funkce
      href: ./ansible-matrix.md
    - name: Azure Container Instances
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_acs_module.html'
    - name: Azure Functions
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html'
    - name: Nástroje pro vyrovnávání zatížení
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html'
    - name: Virtuální počítače
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html'
    - name: Všechny moduly pro Azure
      href: 'http://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure'