### YamlMime:YamlDocument
documentType: LandingData
title: Dokumentace ke službě Azure Container Service s protokolem Kubernetes
metadata:
  document_id: null
  title: 'Dokumentace ke službě Azure Container Service s protokolem Kubernetes – kurzy, reference k rozhraní API | Dokumentace Microsoftu'
  meta.description: 'Azure Container Service allows you to quickly deploy a production ready Kubernetes cluster. Learn how to use Azure Container Service in concert with Kubernetes with these quickstarts, tutorials, and samples.'
  services: container-service
  author: carolz
  manager: carolz
  ms.service: container-service
  ms.tgt_pltfrm: na
  ms.devlang: na
  ms.topic: landing-page
  ms.date: 07-21-2017
  ms.author: carolz
abstract:
  description: 'Azure Container Service umožňuje rychle nastavit cluster Kubernetes připravený pro produkční prostředí. Naučte se prostřednictvím těchto šablon Rychlý start, kurzů a ukázek používat službu Azure Container Service společně s protokolem Kubernetes.'
sections:
  - title: Zprovoznění během 5 minut
    items:
      - type: paragraph
        text: 'Podívejte se, jak nasadit clustery Kubernetes pomocí služby Azure Container Service:'
      - type: list
        style: icon48
        items:
          - image:
              src: 'https://docs.microsoft.com/media/logos/logo_linux.svg'
            text: Vytvoření clusteru Kubernetes
            href: /azure/container-service/kubernetes/container-service-kubernetes-walkthrough
  - title: Podrobné kurzy
    items:
      - type: paragraph
        text: 'Naučte se nasazovat, spravovat a aktualizovat aplikace v clusteru Kubernetes se službou Azure Container Service.'
      - type: list
        style: ordered
        items:
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-prepare-app">Vytvoření imagí kontejneru z aplikace</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-prepare-acr">Nahrání imagí kontejneru do Azure Container Registry</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-deploy-cluster">Nasazení clusteru Kubernetes ve službě Azure Container Service</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-deploy-application">Spuštění imagí kontejneru v Kubernetes</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-scale">Škálování aplikace a infrastruktury Kubernetes</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-app-update">Aktualizace aplikace běžící v Kubernetes</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-monitor">Monitorování Kubernetes pomocí OMS</a>
  - title: Ukázky
    items:
      - type: list
        style: unordered
        className: spaced noBullet
        items:
          - html: <a href="/azure/container-service/cli-samples">Azure CLI</a>
  - title: Referenční informace
    items:
      - type: list
        style: cards
        className: cardsD
        items:
          - title: Příkazový řádek
            html: <p><a href="/cli/azure/acs">Azure CLI</a></p>
          - title: REST
            html: <p><a href="/rest/api/container-services">REST API</a></p>