- name: ACS s protokolem Kubernetes
  href: ./index.yml
- name: Přehled
  items:
    - name: Služba Container Service
      href: container-service-intro-kubernetes.md
- name: Šablony Rychlý start
  expanded: true
  items:
    - name: Kubernetes Linux
      href: container-service-kubernetes-walkthrough.md
- name: Kurzy
  items:
    - name: 1. Vytvoření imagí kontejneru
      href: container-service-tutorial-kubernetes-prepare-app.md
    - name: 2. Vytvoření registru kontejneru
      href: container-service-tutorial-kubernetes-prepare-acr.md
    - name: 3. Vytvoření clusteru Kubernetes
      href: container-service-tutorial-kubernetes-deploy-cluster.md
    - name: 4. Spuštění aplikace
      href: container-service-tutorial-kubernetes-deploy-application.md
    - name: 5. Škálování aplikace
      href: container-service-tutorial-kubernetes-scale.md
    - name: 6. Aktualizace aplikace
      href: container-service-tutorial-kubernetes-app-update.md
    - name: 7. Monitorování pomocí OMS
      href: container-service-tutorial-kubernetes-monitor.md
- name: Ukázky
  items:
    - name: Azure CLI
      href: cli-samples.md
- name: Koncepty
  items:
    - name: Zabezpečené kontejnery
      href: container-service-security.md
    - name: Instanční objekt – Kubernetes
      href: container-service-kubernetes-service-principal.md
- name: Návody
  items:
    - name: Rychlý start pro Kubernetes s Windows
      href: container-service-kubernetes-windows-walkthrough.md
    - name: Správa kontejnerů – uživatelské rozhraní Kubernetes
      href: container-service-kubernetes-ui.md
    - name: Nasazení diagramů Helmu
      href: container-service-kubernetes-helm.md
    - name: Průběžná integrace a doručování s využitím Kubernetes a Jenkinse
      href: container-service-kubernetes-jenkins.md
    - name: Použití konceptu s ACR a ACS
      href: container-service-draft-up.md
    - name: Připojení ke clusteru ACS
      href: container-service-connect.md
    - name: Škálování clusteru ACS
      href: container-service-scale.md
    - name: Monitorování
      items:
        - name: Monitorování pomocí služby Datadog
          href: container-service-kubernetes-datadog.md
        - name: Monitorování pomocí služby Sysdig
          href: container-service-kubernetes-sysdig.md
        - name: Monitorování pomocí služby CoScale
          href: container-service-kubernetes-coscale.md
    - name: Nasazení aplikací Spring Boot
      items:
        - name: Nasazení aplikace Spring Boot Application v Linuxu ve službě Azure Container Service
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Nasazení aplikace Spring Boot Application v clusteru Kubernetes ve službě Azure Container Service
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
- name: Referenční informace
  items:
    - name: Azure CLI 2.0
      href: /cli/azure/acs
    - name: REST
      href: /rest/api/compute/containerservices
- name: Zdroje a prostředky
  items:
    - name: Plány Azure do budoucna
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Nejčastější dotazy
      href: container-service-faq.md
    - name: Šablony – modul ACS
      href: 'https://github.com/Azure/acs-engine'
    - name: Ceny
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: Dostupnost v oblastech
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Stack Overflow
      href: 'http://stackoverflow.com/questions/tagged/azure-container-service'
    - name: Videa
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'